<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)!Служебные/obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)!Служебные/bin/$(MSBuildProjectName)/</BaseOutputPath>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
</Project>
